// This file was generated by counterfeiter
package fakes

import (
	"github.com/concourse/atc/api/buildserver"

	"sync"
)

type FakeJobIsPublicDB struct {
	JobIsPublicStub        func(jobName string) (bool, error)
	jobIsPublicMutex       sync.RWMutex
	jobIsPublicArgsForCall []struct {
		jobName string
	}
	jobIsPublicReturns struct {
		result1 bool
		result2 error
	}
}

func (fake *FakeJobIsPublicDB) JobIsPublic(jobName string) (bool, error) {
	fake.jobIsPublicMutex.Lock()
	fake.jobIsPublicArgsForCall = append(fake.jobIsPublicArgsForCall, struct {
		jobName string
	}{jobName})
	fake.jobIsPublicMutex.Unlock()
	if fake.JobIsPublicStub != nil {
		return fake.JobIsPublicStub(jobName)
	} else {
		return fake.jobIsPublicReturns.result1, fake.jobIsPublicReturns.result2
	}
}

func (fake *FakeJobIsPublicDB) JobIsPublicCallCount() int {
	fake.jobIsPublicMutex.RLock()
	defer fake.jobIsPublicMutex.RUnlock()
	return len(fake.jobIsPublicArgsForCall)
}

func (fake *FakeJobIsPublicDB) JobIsPublicArgsForCall(i int) string {
	fake.jobIsPublicMutex.RLock()
	defer fake.jobIsPublicMutex.RUnlock()
	return fake.jobIsPublicArgsForCall[i].jobName
}

func (fake *FakeJobIsPublicDB) JobIsPublicReturns(result1 bool, result2 error) {
	fake.JobIsPublicStub = nil
	fake.jobIsPublicReturns = struct {
		result1 bool
		result2 error
	}{result1, result2}
}

var _ buildserver.JobIsPublicDB = new(FakeJobIsPublicDB)
