// Code generated by counterfeiter. DO NOT EDIT.
package dbfakes

import (
	"sync"

	"github.com/concourse/atc/db"
)

type FakeSpaceJobFactory struct {
	PipelineJobsStub        func(string, string) (db.SpaceDashboard, error)
	pipelineJobsMutex       sync.RWMutex
	pipelineJobsArgsForCall []struct {
		arg1 string
		arg2 string
	}
	pipelineJobsReturns struct {
		result1 db.SpaceDashboard
		result2 error
	}
	pipelineJobsReturnsOnCall map[int]struct {
		result1 db.SpaceDashboard
		result2 error
	}
	VisibleJobsStub        func([]string) (db.SpaceDashboard, error)
	visibleJobsMutex       sync.RWMutex
	visibleJobsArgsForCall []struct {
		arg1 []string
	}
	visibleJobsReturns struct {
		result1 db.SpaceDashboard
		result2 error
	}
	visibleJobsReturnsOnCall map[int]struct {
		result1 db.SpaceDashboard
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSpaceJobFactory) PipelineJobs(arg1 string, arg2 string) (db.SpaceDashboard, error) {
	fake.pipelineJobsMutex.Lock()
	ret, specificReturn := fake.pipelineJobsReturnsOnCall[len(fake.pipelineJobsArgsForCall)]
	fake.pipelineJobsArgsForCall = append(fake.pipelineJobsArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("PipelineJobs", []interface{}{arg1, arg2})
	fake.pipelineJobsMutex.Unlock()
	if fake.PipelineJobsStub != nil {
		return fake.PipelineJobsStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.pipelineJobsReturns.result1, fake.pipelineJobsReturns.result2
}

func (fake *FakeSpaceJobFactory) PipelineJobsCallCount() int {
	fake.pipelineJobsMutex.RLock()
	defer fake.pipelineJobsMutex.RUnlock()
	return len(fake.pipelineJobsArgsForCall)
}

func (fake *FakeSpaceJobFactory) PipelineJobsArgsForCall(i int) (string, string) {
	fake.pipelineJobsMutex.RLock()
	defer fake.pipelineJobsMutex.RUnlock()
	return fake.pipelineJobsArgsForCall[i].arg1, fake.pipelineJobsArgsForCall[i].arg2
}

func (fake *FakeSpaceJobFactory) PipelineJobsReturns(result1 db.SpaceDashboard, result2 error) {
	fake.PipelineJobsStub = nil
	fake.pipelineJobsReturns = struct {
		result1 db.SpaceDashboard
		result2 error
	}{result1, result2}
}

func (fake *FakeSpaceJobFactory) PipelineJobsReturnsOnCall(i int, result1 db.SpaceDashboard, result2 error) {
	fake.PipelineJobsStub = nil
	if fake.pipelineJobsReturnsOnCall == nil {
		fake.pipelineJobsReturnsOnCall = make(map[int]struct {
			result1 db.SpaceDashboard
			result2 error
		})
	}
	fake.pipelineJobsReturnsOnCall[i] = struct {
		result1 db.SpaceDashboard
		result2 error
	}{result1, result2}
}

func (fake *FakeSpaceJobFactory) VisibleJobs(arg1 []string) (db.SpaceDashboard, error) {
	var arg1Copy []string
	if arg1 != nil {
		arg1Copy = make([]string, len(arg1))
		copy(arg1Copy, arg1)
	}
	fake.visibleJobsMutex.Lock()
	ret, specificReturn := fake.visibleJobsReturnsOnCall[len(fake.visibleJobsArgsForCall)]
	fake.visibleJobsArgsForCall = append(fake.visibleJobsArgsForCall, struct {
		arg1 []string
	}{arg1Copy})
	fake.recordInvocation("VisibleJobs", []interface{}{arg1Copy})
	fake.visibleJobsMutex.Unlock()
	if fake.VisibleJobsStub != nil {
		return fake.VisibleJobsStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.visibleJobsReturns.result1, fake.visibleJobsReturns.result2
}

func (fake *FakeSpaceJobFactory) VisibleJobsCallCount() int {
	fake.visibleJobsMutex.RLock()
	defer fake.visibleJobsMutex.RUnlock()
	return len(fake.visibleJobsArgsForCall)
}

func (fake *FakeSpaceJobFactory) VisibleJobsArgsForCall(i int) []string {
	fake.visibleJobsMutex.RLock()
	defer fake.visibleJobsMutex.RUnlock()
	return fake.visibleJobsArgsForCall[i].arg1
}

func (fake *FakeSpaceJobFactory) VisibleJobsReturns(result1 db.SpaceDashboard, result2 error) {
	fake.VisibleJobsStub = nil
	fake.visibleJobsReturns = struct {
		result1 db.SpaceDashboard
		result2 error
	}{result1, result2}
}

func (fake *FakeSpaceJobFactory) VisibleJobsReturnsOnCall(i int, result1 db.SpaceDashboard, result2 error) {
	fake.VisibleJobsStub = nil
	if fake.visibleJobsReturnsOnCall == nil {
		fake.visibleJobsReturnsOnCall = make(map[int]struct {
			result1 db.SpaceDashboard
			result2 error
		})
	}
	fake.visibleJobsReturnsOnCall[i] = struct {
		result1 db.SpaceDashboard
		result2 error
	}{result1, result2}
}

func (fake *FakeSpaceJobFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.pipelineJobsMutex.RLock()
	defer fake.pipelineJobsMutex.RUnlock()
	fake.visibleJobsMutex.RLock()
	defer fake.visibleJobsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSpaceJobFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ db.SpaceJobFactory = new(FakeSpaceJobFactory)
