// Code generated by counterfeiter. DO NOT EDIT.
package dbfakes

import (
	"sync"

	"github.com/concourse/atc/db"
)

type FakeWorkerTaskCacheFactory struct {
	FindStub        func(jobCombinationID int, stepName string, path string, workerName string) (*db.UsedWorkerTaskCache, bool, error)
	findMutex       sync.RWMutex
	findArgsForCall []struct {
		jobCombinationID int
		stepName         string
		path             string
		workerName       string
	}
	findReturns struct {
		result1 *db.UsedWorkerTaskCache
		result2 bool
		result3 error
	}
	findReturnsOnCall map[int]struct {
		result1 *db.UsedWorkerTaskCache
		result2 bool
		result3 error
	}
	FindOrCreateStub        func(jobCombinationID int, stepName string, path string, workerName string) (*db.UsedWorkerTaskCache, error)
	findOrCreateMutex       sync.RWMutex
	findOrCreateArgsForCall []struct {
		jobCombinationID int
		stepName         string
		path             string
		workerName       string
	}
	findOrCreateReturns struct {
		result1 *db.UsedWorkerTaskCache
		result2 error
	}
	findOrCreateReturnsOnCall map[int]struct {
		result1 *db.UsedWorkerTaskCache
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeWorkerTaskCacheFactory) Find(jobCombinationID int, stepName string, path string, workerName string) (*db.UsedWorkerTaskCache, bool, error) {
	fake.findMutex.Lock()
	ret, specificReturn := fake.findReturnsOnCall[len(fake.findArgsForCall)]
	fake.findArgsForCall = append(fake.findArgsForCall, struct {
		jobCombinationID int
		stepName         string
		path             string
		workerName       string
	}{jobCombinationID, stepName, path, workerName})
	fake.recordInvocation("Find", []interface{}{jobCombinationID, stepName, path, workerName})
	fake.findMutex.Unlock()
	if fake.FindStub != nil {
		return fake.FindStub(jobCombinationID, stepName, path, workerName)
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fake.findReturns.result1, fake.findReturns.result2, fake.findReturns.result3
}

func (fake *FakeWorkerTaskCacheFactory) FindCallCount() int {
	fake.findMutex.RLock()
	defer fake.findMutex.RUnlock()
	return len(fake.findArgsForCall)
}

func (fake *FakeWorkerTaskCacheFactory) FindArgsForCall(i int) (int, string, string, string) {
	fake.findMutex.RLock()
	defer fake.findMutex.RUnlock()
	return fake.findArgsForCall[i].jobCombinationID, fake.findArgsForCall[i].stepName, fake.findArgsForCall[i].path, fake.findArgsForCall[i].workerName
}

func (fake *FakeWorkerTaskCacheFactory) FindReturns(result1 *db.UsedWorkerTaskCache, result2 bool, result3 error) {
	fake.FindStub = nil
	fake.findReturns = struct {
		result1 *db.UsedWorkerTaskCache
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeWorkerTaskCacheFactory) FindReturnsOnCall(i int, result1 *db.UsedWorkerTaskCache, result2 bool, result3 error) {
	fake.FindStub = nil
	if fake.findReturnsOnCall == nil {
		fake.findReturnsOnCall = make(map[int]struct {
			result1 *db.UsedWorkerTaskCache
			result2 bool
			result3 error
		})
	}
	fake.findReturnsOnCall[i] = struct {
		result1 *db.UsedWorkerTaskCache
		result2 bool
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeWorkerTaskCacheFactory) FindOrCreate(jobCombinationID int, stepName string, path string, workerName string) (*db.UsedWorkerTaskCache, error) {
	fake.findOrCreateMutex.Lock()
	ret, specificReturn := fake.findOrCreateReturnsOnCall[len(fake.findOrCreateArgsForCall)]
	fake.findOrCreateArgsForCall = append(fake.findOrCreateArgsForCall, struct {
		jobCombinationID int
		stepName         string
		path             string
		workerName       string
	}{jobCombinationID, stepName, path, workerName})
	fake.recordInvocation("FindOrCreate", []interface{}{jobCombinationID, stepName, path, workerName})
	fake.findOrCreateMutex.Unlock()
	if fake.FindOrCreateStub != nil {
		return fake.FindOrCreateStub(jobCombinationID, stepName, path, workerName)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.findOrCreateReturns.result1, fake.findOrCreateReturns.result2
}

func (fake *FakeWorkerTaskCacheFactory) FindOrCreateCallCount() int {
	fake.findOrCreateMutex.RLock()
	defer fake.findOrCreateMutex.RUnlock()
	return len(fake.findOrCreateArgsForCall)
}

func (fake *FakeWorkerTaskCacheFactory) FindOrCreateArgsForCall(i int) (int, string, string, string) {
	fake.findOrCreateMutex.RLock()
	defer fake.findOrCreateMutex.RUnlock()
	return fake.findOrCreateArgsForCall[i].jobCombinationID, fake.findOrCreateArgsForCall[i].stepName, fake.findOrCreateArgsForCall[i].path, fake.findOrCreateArgsForCall[i].workerName
}

func (fake *FakeWorkerTaskCacheFactory) FindOrCreateReturns(result1 *db.UsedWorkerTaskCache, result2 error) {
	fake.FindOrCreateStub = nil
	fake.findOrCreateReturns = struct {
		result1 *db.UsedWorkerTaskCache
		result2 error
	}{result1, result2}
}

func (fake *FakeWorkerTaskCacheFactory) FindOrCreateReturnsOnCall(i int, result1 *db.UsedWorkerTaskCache, result2 error) {
	fake.FindOrCreateStub = nil
	if fake.findOrCreateReturnsOnCall == nil {
		fake.findOrCreateReturnsOnCall = make(map[int]struct {
			result1 *db.UsedWorkerTaskCache
			result2 error
		})
	}
	fake.findOrCreateReturnsOnCall[i] = struct {
		result1 *db.UsedWorkerTaskCache
		result2 error
	}{result1, result2}
}

func (fake *FakeWorkerTaskCacheFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.findMutex.RLock()
	defer fake.findMutex.RUnlock()
	fake.findOrCreateMutex.RLock()
	defer fake.findOrCreateMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeWorkerTaskCacheFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ db.WorkerTaskCacheFactory = new(FakeWorkerTaskCacheFactory)
